### ISSUE TITLE
Current bitcoin fork version out of date + can result in segfault

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/sv2-workshop#9]
# Background
Currently, the workshop uses the [`sv2-tp-0.1.3`](https://github.com/Sjors/bitcoin/releases/tag/sv2-tp-0.1.3) tag. This was the most updated tag that worked reliably.

On 2024.08.09, @Sjors released a new [`sv2-tp-0.1.9`](https://github.com/Sjors/bitcoin/releases/tag/sv2-tp-0.1.9) tag that fixes the `0.1.5` segfault @plebhash and I encountered when playing around with the workshop.

# Problem
The workshop should be using the most recent tag.

# Solution
Update the [`Dockerfile`](https://github.com/stratum-mining/sv2-workshop/blob/bf2d39f20fc8545ecfee6489c8f1fefbd04deb0e/materials/Dockerfile#L47) to checkout the `sv2-tp-0.1.9`. Run the workshop and verify no seg fault (or other error) is encountered. Update any documentation referencing the tag.

> Note: The `sv2-tp-0.1.9` is based on the `master` of Bitcoin Core on 2024.09.03 which introduces `cmake`. This will require different packages and install commands.

**Comment by Sjors** [comment]
I didn't test if it fixes the segfault though, you did?

**Comment by rrybarczyk** [comment]
@Sjors No I did not. I misunderstood and thought this update did fix that. I will try with version and see how it works and report any bugs/segfaults.

**Comment by Sjors** [comment]
0.1.5 has broken noise encryption (regression), so be sure to use 0.1.7

I got a crash when testing in 0.1.7 too, but haven't had a chance to investigate. So it's possibly there's still a bug in there.

**Comment by Sjors** [comment]
That crash should be gone in v0.1.9, otherwise please report.

**Comment by rrybarczyk** [comment]
> That crash should be gone in v0.1.9, otherwise please report.

It worked for me when I ran all the roles. However the real test will be running it in a proper workshop. I am optimistic, however.

**Comment by Sjors** [comment]
Feel free to ping me when you know the date of upcoming workshop(s). I can try to bake a fresh release before it.
